config/routes.rb
Rails.application.routes.draw do
  root "lists#index"
  resources :lists
  resources :tasks, except: [:index, :show, :destroy]
  get "archived", to: "lists#archived"
  get "lists/:id/complete", to: "lists#complete", as: "complete"
  get "tasks/:id/change_status", to: "tasks#change_status"
  put "remove_file", to: "tasks#remove_file"
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  validates :title, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  validates :title, presence: true
  has_attached_file :file, default_url: ""
  validates_attachment_content_type :file,
    content_type: ["image/jpeg", "image/gif", "image/png", "application/pdf"],
    size: { in: 0.. 2.megabytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @lists = List.where(archived: false)
  end

  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks.where(complete: false).order(sort_column + " " + sort_direction)
  end

  def complete
    @list = List.find(params[:id])
    @tasks = @list.tasks.where(complete: true).order(sort_column + " " + sort_direction)
  end

  def new
    @list = List.new
  end

  def create
    list = List.create(list_params)

    redirect_to list_path(list)
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update_attributes(list_params)

    if list.archived
      redirect_to lists_path
    else
      redirect_to list_path(id: params[:id])
    end
  end

  def destroy
    List.find(params[:id]).delete

    redirect_to archived_path
  end

  def archived
    @lists = List.where(archived: true)
  end

  private

  def list_params
    params.require(:list).permit(:title, :archived)
  end

  def sort_column
    Task.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new(list_id: params[:list_id])
  end

  def create
    task = Task.create(task_params)

    redirect_to list_path(id: task.list_id)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update_attributes(task_params)

    redirect_to list_path(id: task.list_id)
  end

  def change_status
    task = Task.find(params[:id])
    task.update_attributes(task_params)

    redirect_to root_path
  end

  def remove_file
    task = Task.find(params[:id])
    task.file = nil
    task.save

    redirect_to list_path(id: task.list_id)
  end

  private

  def task_params
    params.require(:task)
      .permit(:title, :complete, :description, :due_date, :list_id, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task Master</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1><%= link_to "Task Master!!!", root_path %></h1>

<%= yield %>

</body>
</html>

app/views/lists/archived.html.erb
<h2>Archived Lists</h2>
<%= link_to "Active Lists", root_path, class:"btn btn-default" %>
<div class="active-lists">
  <% @lists.each do |list| %>
    <div class="list">
      <ul id="list-<%=list.id%>">
        <h2><%= link_to list.title, list_path(list) %></h2>
        <%= link_to "Update", edit_list_path(list), class: "btn btn-default"%>
        <% if list.archived %>
          <%= link_to "Delete", list, method: :delete, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "Archive", list_path(id: list.id, list: { archived: true }), method: :put, class: "btn btn-danger" %>
        <% end %>
        <% list.tasks.each do |task| %>
          <li><%= task.title %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/lists/complete.html.erb
<h3><%= @list.title %></h3>
<p><label>Search tasks: <input type="text" id="title-box" value=""></label></p>
<table class="table table-resposive table-striped">
  <thead>
    <tr class="head">
      <td><%= sortable "title", "Task" %></td>
      <td>Description</td>
      <td><%= sortable "due_date", "Due Date" %></td>
      <td><%= sortable "complete", "Completed?" %></td>
      <td>Mark Incomplete</td>
      <td>Update</td>
    </tr>
  </thead>
  <% @tasks.each do |task| %>
  <tr id="<%= task.id %>">
    <td><%= task.title %></td>
    <td><%= task.description %></td>
    <td><%= task.due_date %></td>
    <td><%= task.complete %></td>
    <td><button class="mark-incomplete btn btn-danger">Mark Incomplete</button></td>
    <td><%= link_to "Update", edit_task_path(task), class: "btn btn-default"%></td>
  </tr>
  <% end %>
</table>

<%= link_to "Tasks in Progress", list_path(@list.id), class:"btn btn-default" %>

app/views/lists/edit.html.erb
<%= form_for @list do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  <%= f.submit "Update"%>
<% end %>

app/views/lists/index.html.erb
<%= link_to "New List", new_list_path, class: "btn btn-default" %>
<%= link_to "Archived Lists", archived_path, class:"btn btn-default" %>

<h2>Active Lists</h2>
<div class="active-lists">
  <% @lists.each do |list| %>
    <div class="list">
      <ul id="list-<%=list.id%>">
        <h2><%= link_to list.title, list_path(list) %></h2>
        <%= link_to "Update", edit_list_path(list), class: "btn btn-default"%>
        <% if list.archived %>
          <%= link_to "Delete", list, method: :delete, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "Archive", list_path(id: list.id, list: { archived: true }), method: :put, class: "btn btn-danger" %>
        <% end %>
        <% list.tasks.each do |task| %>
          <li><%= task.title %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= form_for @list do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  <%= f.submit "Create"%>
<% end %>

app/views/lists/show.html.erb
<h3><%= @list.title %></h3>
<p><label>Search tasks: <input type="text" id="title-box" value=""></p>
<table class="table table-resposive table-striped">
  <thead>
    <tr class="head">
      <td><%= sortable "title", "Task" %></td>
      <td>Description</td>
      <td><%= sortable "due_date", "Due Date" %></td>
      <td><%= sortable "complete", "Completed?" %></td>
      <td>Mark Complete</td>
      <td>Update</td>
    </tr>
  </thead>
  <% @tasks.each do |task| %>
  <tr id="<%= task.id %>">
    <td><%= task.title %></td>
    <td><%= task.description %></td>
    <td><%= task.due_date %></td>
    <td><%= task.complete %></td>
    <td><button class="mark-complete btn btn-default">Mark Complete</button></td>
    <td><%= link_to "Update", edit_task_path(task), class: "btn btn-default"%></td>
  </tr>
  <% end %>
</table>

<%= link_to "Add new task", new_task_path(list_id: @list.id), class: "btn btn-default" %>
<%= link_to "Completed Tasks", complete_path(@list.id), class:"btn btn-default" %>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  <%= f.label "Description" %>
  <%= f.text_field :description %>
  <%= f.label "Due date" %>
  <%= f.date_field :due_date %></br>

  <%= f.hidden_field :list_id, value: @task.list_id %>
  <%= f.file_field :file %>
  <%= f.submit "Update", class: "btn btn-default"%>
<% end %>
<% if @task.file.url.present? %>
  <%= link_to "Current file", @task.file.url %>
  <%= link_to "Delete file", remove_file_path({id: @task.id}), method: :put, class: "btn btn-danger" %>
<% end %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  <%= f.label "Description" %>
  <%= f.text_field :description %>
  <%= f.label "Due date" %>
  <%= f.date_field :due_date %>
  <%= f.hidden_field :list_id, value: @task.list_id %>
  <%= f.file_field :file %>
  <%= f.submit "Create"%>
<% end %>